server:
  port: 9001


mybatis:
  mapper-locations: classpath:cn/keats/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true

spring:
  datasource:
    url: jdbc:mysql://192.168.25.128:3306/mysql?characterEncoding=UTF-8&useSSL=false&serverTimezone=CTT
    driver-class-name: com.mysql.jdbc.Driver
    password: 521
    username: keats
